In [1]:
import numpy as np


In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
arr + arr  # numpy double the elemnt of array


array([0, 2, 4, 6, 8])

In [6]:
arr + 100


array([100, 101, 102, 103, 104])

In [7]:
arr ** 2   # power of 2


array([ 0,  1,  4,  9, 16])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [9]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])