In [1]:
list = [1,2,3,4]
list


[1, 2, 3, 4]

In [2]:
list

[1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
arr = np.array(list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
np.arange(0,12) # for rage of array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.arange(0,12,2) # 1st argument starting index, 2nd range and 3rd how much you increment?

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5) # This zeros function will create n array of n numbers zero.

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5)) # first argument for row and 2nd argument for column

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(1,5,10) # generate 10 elements of array range between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
# 1st argumant og linspace is start , 2nd is finish range and 3rd is number of elements in array.

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5) # for random number

array([0.9165639 , 0.28037401, 0.03510935, 0.64710819, 0.22684389])

In [20]:
np.random.randint(1,100,10) 

array([ 6,  5, 19,  3, 18,  2, 47, 32, 24, 28])

In [ ]:
# generate random integer between 1st and 2nd argument of randint and 3rd ar