In [1]:
list = [1,2,3,4]
list


[1, 2, 3, 4]

In [2]:
list

[1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
arr = np.array(list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
np.arange(0,12) # for rage of array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.arange(0,12,2) # 1st argument starting index, 2nd range and 3rd how much you increment?

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5) # This zeros function will create n array of n numbers zero.

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5)) # first argument for row and 2nd argument for column

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])